credentials:
  usernames:
    user1:
      email: user1@example.com
      name: User One
      password: hello  # Encrypted password
    user2:
      email: user2@example.com
      name: User Two
      password: hello

cookie:
  expiry_days: 30
  key: 'random_signature_key'
  name: 'streamlit_auth_cookie'

preauthorized:
  emails:
  - preauthorized@example.com
